version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
    volumes:
      - db:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  python_football_data:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile_football_data
    logging:
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - .:/output

  python_report:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile_report
    logging:
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
      python_football_data:
        condition: service_completed_successfully
    networks:
      - backend
    volumes:
      - .:/output

volumes:
  db:
    driver: local

networks:
  backend:
